# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'u.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 540)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(70, 270, 161, 51))
        self.label_4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n""")
        self.label_4.setObjectName("label_4")
        self.amountLineEdit = QtWidgets.QLineEdit(Dialog)
        self.amountLineEdit.setGeometry(QtCore.QRect(50, 330, 201, 31))
        self.amountLineEdit.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.amountLineEdit.setObjectName("amountLineEdit")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(70, 440, 156, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.toComboBox = QtWidgets.QComboBox(Dialog)
        self.toComboBox.setGeometry(QtCore.QRect(50, 230, 201, 31))
        self.toComboBox.setObjectName("toComboBox")
        self.errorLabel = QtWidgets.QLabel(Dialog)
        self.errorLabel.setGeometry(QtCore.QRect(70, 480, 161, 41))
        self.errorLabel.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n""color: rgb(255, 0, 0);\n""")
        self.errorLabel.setObjectName("errorLabel")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(70, 60, 161, 51))
        self.label_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n""")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 10, 161, 51))
        self.label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n""")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(70, 170, 161, 51))
        self.label_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n""")
        self.label_3.setObjectName("label_3")
        self.fromComboBox = QtWidgets.QComboBox(Dialog)
        self.fromComboBox.setGeometry(QtCore.QRect(50, 130, 201, 31))
        self.fromComboBox.setObjectName("fromComboBox")
        self.convAmountLabel = QtWidgets.QLabel(Dialog)
        self.convAmountLabel.setGeometry(QtCore.QRect(70, 370, 211, 51))
        self.convAmountLabel.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n""")
        self.convAmountLabel.setObjectName("convAmountLabel")

        self.fromComboBox.addItem(self.onLoad())
        self.fromComboBox.setCurrentIndex(0)
        self.toComboBox.addItem(self.onLoad())
        self.toComboBox.setCurrentIndex(0)
        self.buttonBox.accepted.connect(self.pressed)
        self.buttonBox.rejected.connect(Dialog.reject)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "Amount"))
        self.amountLineEdit.setText(_translate("Dialog", ""))
        self.errorLabel.setText(_translate("Dialog", ""))
        self.label_2.setText(_translate("Dialog", "Starting Currency"))
        self.label.setText(_translate("Dialog", "Currency Converter"))
        self.label_3.setText(_translate("Dialog", "Change Into"))
        self.convAmountLabel.setText(_translate("Dialog", "Amount"))

    def onLoad(self):
        import requests
        url = 'https://api.exchangerate.host/latest'
        res = requests.get(url)
        data = res.json()
        excRates = data['rates']
        keys = []
        for key in excRates.keys():
            keys.append(key)
        for k in range(len(keys)):
            self.fromComboBox.addItem(keys[k])
            self.toComboBox.addItem(keys[k])

    def pressed(self):
        self.errorLabel.setText('')
        import requests
        url = 'https://api.exchangerate.host/latest'
        res = requests.get(url)
        data = res.json()
        excRates = data['rates']
        currFrom = self.fromComboBox.currentText()
        currTo = self.toComboBox.currentText()
        amount = self.amountLineEdit.text()
        try:
            toEur = float(amount) / float(excRates[currFrom])
            toWanted = float(toEur) * float(excRates[currTo])
            self.convAmountLabel.setText(str(toWanted))
        except ValueError:
            self.errorLabel.setText('Enter only numbers')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
